services:
  unifi-controller:
    container_name: unifi-controller
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    image: lscr.io/linuxserver/unifi-controller:latest
    ports:
      - 127.0.0.1:8443:8443
      - 8080:8080
      - 3478:3478/udp
      - 10001:10001/udp
      - 8880:8880
      - 8081:8081
      - 3478:3478
    restart: unless-stopped
    volumes:
      - config:/config

volumes:
  config:
